In [1]:
import numpy as np

A= np.random.rand(9)
print(A)

[0.68851359 0.23536068 0.74086735 0.12192053 0.3967907  0.74879549
 0.2888273  0.1080722  0.22371615]


In [2]:
A.ndim, A.size, A.itemsize, A.nbytes, A.dtype 

(1, 9, 8, 72, dtype('float64'))

In [4]:
B= A.reshape(3,3)
print(B)

[[0.68851359 0.23536068 0.74086735]
 [0.12192053 0.3967907  0.74879549]
 [0.2888273  0.1080722  0.22371615]]


In [5]:
np.linalg.matrix_rank(B)

3

In [6]:
np.linalg.det(B)

-0.025261005798564752

In [8]:
BI=np.linalg.inv(B)
print(BI)

[[-0.31053849 -1.08519734  4.66063215]
 [-7.48176817  2.37326665 16.8334127 ]
 [ 4.01519112  0.25456578 -9.67896887]]


In [11]:
M=np.dot(B,BI)
print(M)

[[ 1.00000000e+00  1.47414841e-16 -5.73189421e-16]
 [ 1.11477058e-16  1.00000000e+00  5.85732983e-17]
 [-3.37709888e-17  5.27130568e-17  1.00000000e+00]]


In [14]:
np.allclose(M, np.eye(3))

True

In [16]:
#LINEAR EQUATIONS

X=np.mat('1,-2,1;0,1,-4;-4,5,9')
X

matrix([[ 1, -2,  1],
        [ 0,  1, -4],
        [-4,  5,  9]])

In [18]:
Y=np.mat('1,4,-13').transpose()
Y

matrix([[  1],
        [  4],
        [-13]])

In [19]:
Z=np.linalg.solve(X,Y)
Z

matrix([[30.],
        [16.],
        [ 3.]])

In [20]:
np.dot(X,Z)

matrix([[  1.],
        [  4.],
        [-13.]])

In [25]:
evalues, evectors= np.linalg.eig(B)
print(evalues,'\n', '\n', evectors)

[ 1.11642253  0.27490531 -0.08230741] 
 
 [[-0.81917621 -0.36319591 -0.28802599]
 [-0.47431127  0.92718073 -0.78466539]
 [-0.322458   -0.09178573  0.54894558]]


# ARRAY

In [35]:
C = np.random.rand(100,100)
F = np.asfortranarray(C)

def addrow(x):
    return np.sum(x[:,0])
def addcol(x):
    return np.sum(x[0,:])
 
print("strides:", C.strides,'\n','\n',  C.flags )
print("strides:", F.strides,'\n','\n',  F.flags )

strides: (800, 8) 
 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

strides: (8, 800) 
 
   C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [36]:
%timeit addrow(C)

2.96 µs ± 45.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [37]:
%timeit addrow(F)

2.89 µs ± 17.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [38]:
%timeit addcol(C)

2.94 µs ± 34 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [40]:
%timeit addcol(F)

2.95 µs ± 61.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [42]:
mat1=np.array([1,2])
mat2=np.array([3,4,5])

mat3=np.outer(mat1, mat2)
mat3

array([[ 3,  4,  5],
       [ 6,  8, 10]])

# MASK

In [46]:
P=np.random.rand(5,5)
P


array([[0.861967  , 0.19777719, 0.81783572, 0.1324462 , 0.1640826 ],
       [0.87037605, 0.86892834, 0.38689664, 0.1883746 , 0.13562489],
       [0.2936725 , 0.94145195, 0.14479367, 0.21942912, 0.10391807],
       [0.70695887, 0.34400144, 0.27166783, 0.14364829, 0.48303932],
       [0.72522936, 0.95164837, 0.13531908, 0.74937667, 0.6929856 ]])

In [51]:
mask=(P<0.5)
mask


array([[False,  True, False,  True,  True],
       [False, False,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [False, False,  True, False, False]])

In [49]:
P[mask]=0
P

array([[0.861967  , 0.        , 0.81783572, 0.        , 0.        ],
       [0.87037605, 0.86892834, 0.        , 0.        , 0.        ],
       [0.        , 0.94145195, 0.        , 0.        , 0.        ],
       [0.70695887, 0.        , 0.        , 0.        , 0.        ],
       [0.72522936, 0.95164837, 0.        , 0.74937667, 0.6929856 ]])

In [50]:
P.sum()

8.186757941759764